version: '3.8'
services:
  postgres:
    image: postgres
  flaskapp:
    build: .
    environment: 
      - POSTGRES_USER="username"
      - POSTGRES_PASSWORD="password"
      - POSTGRES_DB="database"
      - POSTGRES_SECRET_KEY="SECRET_KEY"
    ports:
      - "5000:5000"
    depends_on:
      - postgres